#include<iostream>
using namespace std;
class Mystring{
    public:
    int operator-()
    {

    }
    bool operator==()
    {

    }
    bool operator!=()
    {

    }
    bool operator>()
    {

    }
    bool operator<()
    {

    }
    int operator+()
    {

    }
    int operator++()
    {

    }
    int operator*()
    {

    }
    int operator*=()
    {

    }

};
int main()
{

    return 0;
}